# main.yml
on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Operator-SDK K8s Action
      uses: dramirez-qb/operator-sdk-github-action@v3
    - uses: actions/checkout@v3
