# main.yml
on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - uses: .github/actions/operator.yml

